// <auto-generated />
using System;
using AgriLedger.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriLedger.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AgriLedger.API.Models.BagMovement", b =>
            {
                b.Property<string>("Id").HasMaxLength(36).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateOnly>("EntryDate").HasColumnType("TEXT");
                b.Property<string>("LinkedTxnId").HasMaxLength(36).HasColumnType("TEXT");
                b.Property<string>("Movement").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("PartyId").IsRequired().HasMaxLength(36).HasColumnType("TEXT");
                b.Property<int>("Quantity").HasColumnType("INTEGER");
                b.Property<DateTime?>("SyncedAt").HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("EntryDate").HasDatabaseName("IX_BagMovements_EntryDate");
                b.HasIndex("LinkedTxnId").HasDatabaseName("IX_BagMovements_LinkedTxnId");
                b.HasIndex("PartyId").HasDatabaseName("IX_BagMovements_PartyId");
                b.ToTable("BagMovements");
            });

            modelBuilder.Entity("AgriLedger.API.Models.Party", b =>
            {
                b.Property<string>("Id").HasMaxLength(36).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER").HasDefaultValue(true);
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("PartyType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Phone").HasMaxLength(15).HasColumnType("TEXT");
                b.Property<DateTime?>("SyncedAt").HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("Village").HasMaxLength(100).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("IsActive").HasDatabaseName("IX_Parties_IsActive");
                b.HasIndex("Name").HasDatabaseName("IX_Parties_Name");
                b.HasIndex("PartyType").HasDatabaseName("IX_Parties_PartyType");
                b.HasIndex("Village").HasDatabaseName("IX_Parties_Village");
                b.ToTable("Parties");
                b.HasData(new {
                    Id = "00000000-0000-0000-0000-000000000001",
                    Name = "Demo Farmer",
                    PartyType = "farmer",
                    Village = "Demo Village",
                    IsActive = true,
                    CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                    UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                });
            });

            modelBuilder.Entity("AgriLedger.API.Models.SyncQueueItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("EntityId").IsRequired().HasMaxLength(36).HasColumnType("TEXT");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
                b.Property<string>("LastError").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Operation").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("Payload").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime?>("ProcessedAt").HasColumnType("TEXT");
                b.Property<int>("RetryCount").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex(new[] { "EntityType", "CreatedAt" }).HasDatabaseName("IX_SyncQueue_EntityType_CreatedAt");
                b.HasIndex("ProcessedAt").HasDatabaseName("IX_SyncQueue_ProcessedAt");
                b.ToTable("SyncQueue");
            });

            modelBuilder.Entity("AgriLedger.API.Models.Transaction", b =>
            {
                b.Property<string>("Id").HasMaxLength(36).HasColumnType("TEXT");
                b.Property<decimal?>("Amount").HasPrecision(12, 2).HasColumnType("TEXT");
                b.Property<string>("Commodity").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Direction").IsRequired().HasMaxLength(5).HasColumnType("TEXT");
                b.Property<DateOnly>("EntryDate").HasColumnType("TEXT");
                b.Property<bool>("IsDeleted").HasColumnType("INTEGER").HasDefaultValue(false);
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("PartyId").IsRequired().HasMaxLength(36).HasColumnType("TEXT");
                b.Property<string>("PaymentMode").IsRequired().HasMaxLength(10).HasDefaultValue("cash").HasColumnType("TEXT");
                b.Property<decimal?>("QuantityKg").HasPrecision(10, 3).HasColumnType("TEXT");
                b.Property<decimal?>("RatePerKg").HasPrecision(10, 2).HasColumnType("TEXT");
                b.Property<DateTime?>("SyncedAt").HasColumnType("TEXT");
                b.Property<string>("TxnType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("VoiceRaw").HasMaxLength(1000).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("EntryDate").HasDatabaseName("IX_Transactions_EntryDate");
                b.HasIndex("IsDeleted").HasDatabaseName("IX_Transactions_IsDeleted");
                b.HasIndex("PartyId").HasDatabaseName("IX_Transactions_PartyId");
                b.HasIndex("TxnType").HasDatabaseName("IX_Transactions_TxnType");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("AgriLedger.API.Models.BagMovement", b =>
            {
                b.HasOne("AgriLedger.API.Models.Party", "Party")
                 .WithMany("BagMovements").HasForeignKey("PartyId")
                 .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("AgriLedger.API.Models.Transaction", "LinkedTransaction")
                 .WithMany().HasForeignKey("LinkedTxnId")
                 .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("LinkedTransaction");
                b.Navigation("Party");
            });

            modelBuilder.Entity("AgriLedger.API.Models.Transaction", b =>
            {
                b.HasOne("AgriLedger.API.Models.Party", "Party")
                 .WithMany("Transactions").HasForeignKey("PartyId")
                 .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Party");
            });

            modelBuilder.Entity("AgriLedger.API.Models.Party", b =>
            {
                b.Navigation("BagMovements");
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
